tobertrand: 
        repository: ${PATH_EPYTOPE}/../bertrand
        conda: epytope
imrex: 
        conda: deepTCR
ergo-ii: 
        repository: ${PATH_EPYTOPE}/../ERGO-II
        conda: epytope_torch21
ergo-i: 
        repository: ${PATH_EPYTOPE}/../ERGO
        conda: epytope_torch21
titan: 
        conda: epytope_torch11
teinet: 
        repository: ${PATH_EPYTOPE}/../TEINet
        conda: epytope_torch11
epitcr: 
        repository: ${PATH_EPYTOPE}/../epiTCR
        conda: epytope
atm-tcr: 
        repository: ${PATH_EPYTOPE}/../ATM-TCR
        conda: epytope_torch11
        cuda: True
dlptcr: 
        repository: ${PATH_EPYTOPE}/../DLpTCR
        conda: epytope
pmtnet: 
        repository: ${PATH_EPYTOPE}/../pMTnet
        conda: epytope_torch21
attntap: 
        repository: ${PATH_EPYTOPE}/../AttnTAP
        conda: epytope
teim: 
        repository: ${PATH_EPYTOPE}/../TEIM
        conda: epytope
panpep:
        repository: ${PATH_EPYTOPE}/../PanPep
        conda: epytope_torch11
stapler: 
        conda: epytope_stapler
tcellmatch:
        conda: epytope_numpy195
